#pragma once

#define AUTHORS_A "Philip Seitz"
#define AUTHORS_B "Philip Seitz"
#define AUTHORS_C "Bora Büyükbas"
#define AUTHORS_D "Bora Büyükbas"
#define AUTHORS_E "Bora Büyükbas"
#define AUTHORS_F "Bora Büyükbas"
#define AUTHORS_G "Fares Elkholy"
#define AUTHORS_H "Fares Elkholy"
#define AUTHORS_I "Fares Elkholy"
#define AUTHORS_J "Fares Elkholy"
#define AUTHORS_K "Philip Seitz"
#define AUTHORS_L "Philip Seitz"
#define AUTHORS_M "Philip Seitz"
#define AUTHORS_N "Philip Seitz"
