#pragma once

#define AUTHORS_A "Lukas Rothenberger"
#define AUTHORS_B ""
#define AUTHORS_C "Bora Büyükbas"
#define AUTHORS_D "Bora Büyükbas"
#define AUTHORS_E "Bora Büyükbas"
#define AUTHORS_F "Bora Büyükbas"
#define AUTHORS_G ""
#define AUTHORS_H ""
#define AUTHORS_I ""
#define AUTHORS_J ""
#define AUTHORS_K ""
#define AUTHORS_L ""
#define AUTHORS_M ""
#define AUTHORS_N ""
