#pragma once

#define AUTHORS_A "Lukas Rothenberger"
#define AUTHORS_B ""
#define AUTHORS_C "Bora Büyükbas"
#define AUTHORS_D "Bora Büyükbas"
#define AUTHORS_E "Bora Büyükbas"
#define AUTHORS_F "Bora Büyükbas"
#define AUTHORS_G "Fares Elkholy"
#define AUTHORS_H "Fares Elkholy"
#define AUTHORS_I "Fares Elkholy"
#define AUTHORS_J "Fares Elkholy"
#define AUTHORS_K ""
#define AUTHORS_L ""
#define AUTHORS_M ""
#define AUTHORS_N ""
